Refactor urlencodecurl() function and other code

diff --git a/tracker b/tracker
--- a/tracker
+++ b/tracker
@@ -28,22 +28,22 @@ urldecode() {
     printf '%b' "${url_encoded//%/\\x}"
 }
 urlencodecurl() {
-if [[ $# != 1 ]]; then
-echo "Usage: $0 string-to-urlencode"
-return 1
-fi
-local data="$(curl -s -o /dev/null -w %{url_effective} --get --data-urlencode "$1" "")"
-if [[ $? == 0 ]]; then
-echo "${data##/?}"
-fi
-return 0
+  if [ $# -ne 1 ]; then
+    echo "Usage: ${0##*/} string-to-urlencode" >&2
+    return 1
+  fi
+
+  local data
+  if data=$(curl -sS -w %{url_effective} --get --data-urlencode "$1" "" 2>/dev/null); then
+    echo "${data%%$'\n'}"
+  else
+    echo "Error: curl returned non-zero exit code" >&2
+    return 1
+  fi
+
+  return 0
 }
 
-trackerlistgit=$(curl https://ngosang.github.io/trackerslist/trackers_all_ip.txt https://cdn.staticaly.com/gh/XIU2/TrackersListCollection/master/all.txt)
-# This variable doesn't work, 
-# trackerencoder=${${"$(urlencodecurl "$trackerlistgit")"//\%0A/\&tr=}//\&tr=\&tr=/\&tr=}
-aa="$(urlencodecurl "$trackerlistgit")"
-bb="$(sed s'/\%0A/\&tr=/g' <<< "$aa")"
-trackerencoder="$(sed s'/\&tr=\&tr=/\\\&tr=/g' <<< "$bb")"
-# echo $trackerencoder
+trackerlistgit=$(curl -s https://ngosang.github.io/trackerslist/trackers_all_ip.txt https://cdn.staticaly.com/gh/XIU2/TrackersListCollection/master/all.txt)
+trackerencoder=$(urlencodecurl "$trackerlistgit" | sed 's/%0A/\&tr=/g; s/\&tr=\&tr=/\\\&tr=/g')
 sed -i "s/tracker=\".*\"/tracker=\"\&tr=${trackerencoder}\"/g" config
